files:
  include: '**/*.scss'
  ignore: '**/styles.scss'
options:
  formatter: stylish
  merge-default-rules: true
rules:
  bem-depth: 1
  border-zero:
    - 1
    - convention: 0
  class-name-format:
    - 1
    - convention: ^(?!js-).*
      convention-explanation: should not be written in the form js-*
  extends-before-declarations: 0
  extends-before-mixins: 0
  function-name-format: 1
  id-name-format:
    - 1
    - convention: hyphenatedbem
  leading-zero: 0
  mixin-name-format: 1
  mixins-before-declarations: 0
  no-extends: 1
  no-qualifying-elements: 0
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem
  property-sort-order: 0
  quotes:
    - 1
    - style: double
  variable-name-format: 1
  no-css-comments: 0
  hex-notation: 0
  space-before-colon: 0
  force-element-nesting: 0
  nesting-depth: -1
